######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 4 03:54:47 2009
######################################################################

TEMPLATE = app
TARGET = sol
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientprocess.h mainwindow.h
SOURCES += clientprocess.cpp main.cpp mainwindow.cpp
