######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 4 03:54:30 2009
######################################################################

TEMPLATE = app
TARGET = sol_client
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
HEADERS += application.h clientwindow.h
FORMS += clientwidget.ui
SOURCES += application.cpp clientwindow.cpp main.cpp
